// next imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";

// custom imports
import { ThemeProvider } from "@/components/theme-provider";
import { ToastContainer } from "react-toastify";

// css import
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const CheckHomepage = dynamic(
    () => import("@/app/(extra)/_components/CheckHomepage"),
    {
      ssr: false,
    }
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <Script
          src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"
          async
          strategy="beforeInteractive"
        />
        <Script id="interstallar-ads" strategy="beforeInteractive">
          {`
          window.googletag = window.googletag || {cmd: []};
  var interstitialSlot;
  googletag.cmd.push(function() {
    interstitialSlot = googletag.defineOutOfPageSlot('/22989534981/DG_INTERSTITIAL', googletag.enums.OutOfPageFormat.INTERSTITIAL);
    if (interstitialSlot) {
          interstitialSlot.addService(googletag.pubads());
          }
    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
  });`}
        </Script>
        <Script id="inter-ads" strategy="afterInteractive">
          {`googletag.cmd.push(function() {
         googletag.display(interstitialSlot);
        });
`}
        </Script>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <ToastContainer />
          <main className="max-w-screen-xss mx-auto px-2 xxs:px-1">
            {children}
            <CheckHomepage />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
