// next imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";

// custom imports
import { ThemeProvider } from "@/components/theme-provider";
import { ToastContainer, toast } from "react-toastify";

// css import
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const CheckHomepage = dynamic(
    () => import("@/app/(extra)/_components/CheckHomepage"),
    {
      ssr: false,
    }
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <Script src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></Script>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <ToastContainer />
          <main className="max-w-screen-xss mx-auto px-2 xxs:px-1">
            {children}
            <CheckHomepage />
          </main>
        </ThemeProvider>
        <Script id="banner-ad" strategy="lazyOnload">
          {`
          window.googletag = window.googletag || {cmd: []};
            googletag.cmd.push(function() {
              googletag.defineSlot('/22989534981/DG_7_336X280', [336, 280], 'div-gpt-ad-1700655338779-0').addService(googletag.pubads());
              googletag.pubads().enableSingleRequest();
              googletag.enableServices();
            });       
          
          googletag.cmd.push(function() { googletag.display('div-gpt-ad-1700655338779-0'); });`}
        </Script>
      </body>
    </html>
  );
}
