export const category: string[] = [
  "All",
  "Monuments",
  "English Grammar",
  "Famous Personality",
  "Sports",
  "Fun Science",
  "Fun Maths",
  "Bollywood",
  "Birds And Animals",
  "Vocabulary",
  "Automobiles",
  "Food & Beverages",
  "Test Your Knowledge",
  "Entertainment",
  "Business",
  "General Trivia",
  "Litrature",
  "Festivals",
];

export const icons: { [key: string]: string } = {
  Monuments: "monument.png",
  "English Grammar": "grammar.png",
  "Famous Personality": "famous.png",
  Sports: "sports.png",
  "Fun Science": "science.png",
  "Fun Maths": "math.png",
  Bollywood: "bollywood.png",
  "Birds And Animals": "animal.png",
  Vocabulary: "vocab.png",
  Automobiles: "auto.png",
  "Food & Beverages": "food.png",
  "Food Brands": "brand.png",
  "Test Your Knowledge": "testknow.png",
  Entertainment: "entertainment.png",
  Business: "business-min.png",
  "General Trivia": "trivia-min.png",
  Litrature: "literature-min.png",
  Festivals: "festival-min.png",
};
